"""
Cybersecurity Regulatory Compliance ABM Runner
==============================================
Command-line interface to execute the 5-stage simulation, export datasets,
and generate comprehensive, human-auditable results reports including:
  1. Context (T=0) Baseline Table
  2. Longitudinal Stage Trajectory Matrix (Context -> Operating -> Precursors -> Recovering -> Outcomes)
  3. Stage-Specific Behavioral Dashboards (Operating, Precursors, Recovering, Outcomes)
  4. Financial & Enforcement Accounting Ledger
  5. Side-by-Side Empirical Validation Audit Scorecard (Simulated vs. Benchmark Ground Truth)
  6. Automated Markdown Executive Summary Report (outputs/summary_report.md)
"""

import argparse
import json
import logging
import os
import pandas as pd
from datetime import datetime
from model import CyberComplianceModel, EMPIRICAL_PROFILES

logger = logging.getLogger("CyberComplianceModel")


def df_to_markdown(df):
    """Converts a pandas DataFrame to a GitHub-flavored Markdown table without external dependencies."""
    if df is None or df.empty:
        return ""
    headers = [str(c) for c in df.columns]
    header_line = "| " + " | ".join(headers) + " |"
    separator_line = "| " + " | ".join([":---" for _ in headers]) + " |"
    data_lines = []
    for _, row in df.iterrows():
        row_vals = [str(val) for val in row]
        data_lines.append("| " + " | ".join(row_vals) + " |")
    return "\n".join([header_line, separator_line] + data_lines)


def generate_markdown_report(report_path, config, df_initial, trajectory_df, stage_dashboards, audit_df, alignment_score, mae, ledger):
    """Generates an executive markdown report summarizing the entire simulation run."""
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(f"# Simulation Executive Report: {config['scenario'].upper()}\n\n")
        f.write(f"**Description:** {config['description']}\n\n")
        f.write(f"- **Execution Timestamp:** `{config['timestamp']}`\n")
        f.write(f"- **Total Steps:** `{config['steps']}` | **Incident Step:** `{config['incident_step']}` | **Random Seed:** `{config['seed']}`\n")
        f.write(f"- **Empirical Alignment Score:** **`{alignment_score:.1f}%`** (MAE: `{mae:.3f}` on a 1–5 scale)\n\n")
        f.write("---\n\n")

        # 1. Longitudinal Trajectory Matrix
        f.write("## 1. Longitudinal Stage Trajectory Matrix\n\n")
        f.write("Evolution of key system and stakeholder metrics across the 5 lifecycle stages:\n\n")
        f.write(df_to_markdown(trajectory_df) + "\n\n")

        # 2. Stage-Specific Behavioral Dashboards
        f.write("## 2. Stage-Specific Behavioral Dashboards\n\n")

        f.write("### Stage 2: Operating (Baseline Governance & Cyber Hygiene)\n\n")
        f.write(df_to_markdown(stage_dashboards["operating"]) + "\n\n")

        f.write("### Stage 3: Precursors (Vulnerability Window & Risk Build-up)\n\n")
        f.write(df_to_markdown(stage_dashboards["precursors"]) + "\n\n")

        f.write("### Stage 4: Recovering (Crisis Management & Enforcement Stances)\n\n")
        f.write(df_to_markdown(stage_dashboards["recovering"]) + "\n\n")

        f.write("### Stage 5: Outcomes (Systemic Equilibrium & Long-Term Legacy)\n\n")
        f.write(df_to_markdown(stage_dashboards["outcomes"]) + "\n\n")

        # 3. Financial Ledger
        f.write("## 3. Financial & Enforcement Accounting\n\n")
        f.write("| Ledger Metric | Amount ($) |\n| :--- | :--- |\n")
        for k, v in ledger.items():
            if "(%)" in k:
                f.write(f"| {k} | {v:.1f}% |\n")
            else:
                f.write(f"| {k} | ${v:,.2f} |\n")
        f.write("\n")

        # 4. Empirical Validation Audit Scorecard
        if not audit_df.empty:
            f.write("## 4. Empirical Validation Audit Scorecard\n\n")
            f.write("Comparison of terminal simulated outcomes against empirical case study benchmarks:\n\n")
            f.write(df_to_markdown(audit_df) + "\n\n")
            f.write(f"**Overall Model Alignment Score:** `{alignment_score:.1f}%` (Mean Absolute Error: `{mae:.3f}`)\n\n")

        f.write("---\n*Report automatically generated by Cybersecurity Regulatory Compliance ABM Engine.*\n")


def run_simulation(scenario="equifax_2017", steps=30, incident_step=10, seed=42, output_dir="outputs"):
    os.makedirs(output_dir, exist_ok=True)

    if scenario != "random" and scenario not in EMPIRICAL_PROFILES:
        print(f"Error: Unknown scenario '{scenario}'. Available presets: {list(EMPIRICAL_PROFILES.keys())} or 'random'")
        return

    scenario_desc = "Randomly generated stochastic baseline scenario." if scenario == "random" else EMPIRICAL_PROFILES[scenario]["description"]

    print("\n" + "=" * 80)
    print(f"--- RUNNING SCENARIO: {scenario.upper()} ---")
    print(f"Description: {scenario_desc}")
    print(f"Simulation Steps: {steps} | Incident at Step: {incident_step} | Seed: {seed}")
    print("=" * 80)

    config = {
        "scenario": scenario,
        "description": scenario_desc,
        "steps": steps,
        "incident_step": incident_step,
        "seed": seed,
        "timestamp": datetime.now().isoformat()
    }

    config_path = os.path.join(output_dir, "config.json")
    with open(config_path, "w") as f:
        json.dump(config, f, indent=4)

    # Initialize model
    model = CyberComplianceModel(
        scenario_name=scenario,
        total_steps=steps,
        incident_step=incident_step
    )

    # -----------------------------------------------------------------
    # STAGE 1: CONTEXT (T = 0) INITIAL STATE TRANSPARENCY
    # -----------------------------------------------------------------
    print("\n" + "=" * 70)
    print(f"--- STAGE 1: CONTEXT (T = 0 Baseline Setup) [{scenario}] ---")
    print("=" * 70)
    initial_agent_data = []
    for agent in model.schedule.agents:
        initial_agent_data.append({
            "AgentID": agent.unique_id,
            "Type": agent.stakeholder_type,
            "OpCapacity": agent.operational_capacity,
            "RegPressure": agent.regulatory_pressure,
            "ThreatLevel": agent.threat_level,
            "EnvReg": agent.env_regulatory,
            "EnvThreat": agent.env_threat,
            "EnvOp": agent.env_operational
        })
    df_initial = pd.DataFrame(initial_agent_data)
    print(df_initial.to_string(index=False))

    # Context averages for the trajectory matrix
    t0_macro_threat = df_initial["ThreatLevel"].mean()
    t0_macro_opcap = df_initial["OpCapacity"].mean()
    t0_macro_regpress = df_initial["RegPressure"].mean()
    t0_gini = model.calculate_gini(df_initial["ThreatLevel"].tolist())

    t0_reg_op = df_initial[df_initial["Type"] == "regulator"]["OpCapacity"].mean()
    t0_reg_rp = df_initial[df_initial["Type"] == "regulator"]["RegPressure"].mean()

    t0_prod_th = df_initial[df_initial["Type"] == "producer"]["ThreatLevel"].mean()
    t0_prod_op = df_initial[df_initial["Type"] == "producer"]["OpCapacity"].mean()
    t0_prod_rp = df_initial[df_initial["Type"] == "producer"]["RegPressure"].mean()

    t0_user_th = df_initial[df_initial["Type"] == "user"]["ThreatLevel"].mean()
    t0_user_op = df_initial[df_initial["Type"] == "user"]["OpCapacity"].mean()
    t0_user_rp = df_initial[df_initial["Type"] == "user"]["RegPressure"].mean()

    # Run simulation ticks
    for _ in range(steps):
        model.step()

    # Collect outputs
    model_data = model.datacollector.get_model_vars_dataframe()
    agent_data = model.datacollector.get_agent_vars_dataframe()

    model_csv_path = os.path.join(output_dir, "model_output.csv")
    agent_csv_path = os.path.join(output_dir, "agent_output.csv")

    model_data.to_csv(model_csv_path)
    agent_data.to_csv(agent_csv_path)

    print(f"\nSimulation finished successfully!")
    print(f"Results stored in: {os.path.abspath(output_dir)}")

    # -----------------------------------------------------------------
    # LONGITUDINAL STAGE TRAJECTORY MATRIX
    # -----------------------------------------------------------------
    stages = ["Operating", "Precursors", "Recovering", "Outcomes"]
    stage_means = {}
    for stg in stages:
        sub = model_data[model_data["Stage"] == stg]
        if not sub.empty:
            stage_means[stg] = sub.mean(numeric_only=True)
        else:
            stage_means[stg] = pd.Series(dtype=float)

    trajectory_rows = [
        {"Metric / Stakeholder": "Macro Avg Threat", "Context (T0)": round(t0_macro_threat, 2)},
        {"Metric / Stakeholder": "Macro Avg OpCapacity", "Context (T0)": round(t0_macro_opcap, 2)},
        {"Metric / Stakeholder": "Macro Avg RegPressure", "Context (T0)": round(t0_macro_regpress, 2)},
        {"Metric / Stakeholder": "Threat Inequality (Gini)", "Context (T0)": round(t0_gini, 3)},
        {"Metric / Stakeholder": "Regulator OpCapacity", "Context (T0)": round(t0_reg_op, 2)},
        {"Metric / Stakeholder": "Regulator RegPressure", "Context (T0)": round(t0_reg_rp, 2)},
        {"Metric / Stakeholder": "Producer Threat Level", "Context (T0)": round(t0_prod_th, 2)},
        {"Metric / Stakeholder": "Producer OpCapacity", "Context (T0)": round(t0_prod_op, 2)},
        {"Metric / Stakeholder": "Producer RegPressure", "Context (T0)": round(t0_prod_rp, 2)},
        {"Metric / Stakeholder": "User Threat Level", "Context (T0)": round(t0_user_th, 2)},
        {"Metric / Stakeholder": "User OpCapacity", "Context (T0)": round(t0_user_op, 2)},
        {"Metric / Stakeholder": "User RegPressure", "Context (T0)": round(t0_user_rp, 2)},
    ]

    metric_key_map = [
        "AvgThreat", "AvgOperationalCapacity", "AvgRegulatoryPressure", "ThreatGini",
        "Regulator_AvgOpCap", "Regulator_AvgRegPress",
        "Producer_AvgThreat", "Producer_AvgOpCap", "Producer_AvgRegPress",
        "User_AvgThreat", "User_AvgOpCap", "User_AvgRegPress"
    ]

    for idx, key in enumerate(metric_key_map):
        for stg in stages:
            val = stage_means[stg].get(key, None)
            trajectory_rows[idx][stg] = round(val, 2) if val is not None else "-"
        # Compute Net Change (Outcomes - Context)
        out_val = stage_means["Outcomes"].get(key, None)
        t0_val = trajectory_rows[idx]["Context (T0)"]
        if out_val is not None and t0_val != "-":
            change = out_val - t0_val
            sign = "+" if change > 0 else ""
            trajectory_rows[idx]["Net Change"] = f"{sign}{change:.2f}"
        else:
            trajectory_rows[idx]["Net Change"] = "-"

    trajectory_df = pd.DataFrame(trajectory_rows)
    print("\n" + "=" * 80)
    print("--- 1. LONGITUDINAL STAGE TRAJECTORY MATRIX ---")
    print("=" * 80)
    print(trajectory_df.to_string(index=False))

    # -----------------------------------------------------------------
    # STAGE-SPECIFIC BEHAVIORAL DASHBOARDS
    # -----------------------------------------------------------------
    stage_dashboards = {}

    # Stage 2: Operating
    sub_op = model_data[model_data["Stage"] == "Operating"]
    op_means = sub_op.mean(numeric_only=True) if not sub_op.empty else pd.Series(dtype=float)
    op_rows = [
        {"Stakeholder": "Regulator", "Behavior / Node": "Rulemaking", "Simulated Mean": round(op_means.get("Regulator_Rulemaking", 0), 2), "Interpretation": "Regulatory standard setting"},
        {"Stakeholder": "Regulator", "Behavior / Node": "Enforcement", "Simulated Mean": round(op_means.get("Regulator_Enforcement", 0), 2), "Interpretation": "Inspection & citation posture"},
        {"Stakeholder": "Regulator", "Behavior / Node": "Investigation", "Simulated Mean": round(op_means.get("Regulator_Investigation", 0), 2), "Interpretation": "Monitoring & audit intensity"},
        {"Stakeholder": "Software Producer", "Behavior / Node": "Implementing", "Simulated Mean": round(op_means.get("Producer_Implementing", 0), 2), "Interpretation": "Feature rollout velocity"},
        {"Stakeholder": "Software Producer", "Behavior / Node": "Securing", "Simulated Mean": round(op_means.get("Producer_Securing", 0), 2), "Interpretation": "Proactive security hardening"},
        {"Stakeholder": "Software Producer", "Behavior / Node": "Complying", "Simulated Mean": round(op_means.get("Producer_Complying", 0), 2), "Interpretation": "Statutory adherence effort"},
        {"Stakeholder": "Software Producer", "Behavior / Node": "Security Debt Gap", "Simulated Mean": round(op_means.get("Producer_Implementing", 0) - op_means.get("Producer_Securing", 0), 2), "Interpretation": "Implementing minus Securing"},
        {"Stakeholder": "User", "Behavior / Node": "Deploying", "Simulated Mean": round(op_means.get("User_Deploying", 0), 2), "Interpretation": "Client software adoption"},
        {"Stakeholder": "User", "Behavior / Node": "Securing", "Simulated Mean": round(op_means.get("User_Securing", 0), 2), "Interpretation": "User cyber hygiene diligence"},
        {"Stakeholder": "User", "Behavior / Node": "Influencing", "Simulated Mean": round(op_means.get("User_Influencing", 0), 2), "Interpretation": "Advocacy and reporting pressure"}
    ]
    stage_dashboards["operating"] = pd.DataFrame(op_rows)

    # Stage 3: Precursors
    sub_prec = model_data[model_data["Stage"] == "Precursors"]
    prec_means = sub_prec.mean(numeric_only=True) if not sub_prec.empty else pd.Series(dtype=float)
    biz_change = prec_means.get("Producer_BusinessChange", 0)
    unadd_fail = prec_means.get("Producer_Failures", 0)
    prod_cap = prec_means.get("Producer_AvgOpCap", 1)
    risk_index = round((biz_change + unadd_fail) / max(1, prod_cap), 2)
    prec_rows = [
        {"Stakeholder": "Software Producer", "Risk Factor": "Business Change (M&A / Scaling)", "Value (1-5)": round(biz_change, 2), "Risk Signal": "High" if biz_change >= 4 else "Moderate"},
        {"Stakeholder": "Software Producer", "Risk Factor": "Unaddressed Failures & Weaknesses", "Value (1-5)": round(unadd_fail, 2), "Risk Signal": "Critical" if unadd_fail >= 4 else "Moderate"},
        {"Stakeholder": "Regulator", "Risk Factor": "Oversight Capacity Gap", "Value (1-5)": round(prec_means.get("Regulator_PrecursorCapacity", 0), 2), "Risk Signal": "Vulnerable" if prec_means.get("Regulator_PrecursorCapacity", 0) <= 2 else "Adequate"},
        {"Stakeholder": "Ecosystem", "Risk Factor": "Precursor Vulnerability Index", "Value (1-5)": risk_index, "Risk Signal": "Extreme Breach Risk" if risk_index >= 3.0 else "Stable"}
    ]
    stage_dashboards["precursors"] = pd.DataFrame(prec_rows)

    # Stage 4: Recovering
    sub_rec = model_data[model_data["Stage"] == "Recovering"]
    rec_means = sub_rec.mean(numeric_only=True) if not sub_rec.empty else pd.Series(dtype=float)
    rec_rows = [
        {"Stakeholder": "Regulator", "Crisis Stance": "Public Posturing & Scrutiny", "Score (1-5)": round(rec_means.get("Regulator_Posturing", 0), 2)},
        {"Stakeholder": "Regulator", "Crisis Stance": "Correcting & Enforcement Mandates", "Score (1-5)": round(rec_means.get("Regulator_Correcting", 0), 2)},
        {"Stakeholder": "Software Producer", "Crisis Stance": "Posturing (PR / Testimony)", "Score (1-5)": round(rec_means.get("Producer_Posturing", 0), 2)},
        {"Stakeholder": "Software Producer", "Crisis Stance": "Correcting (Remediation & Patching)", "Score (1-5)": round(rec_means.get("Producer_Correcting", 0), 2)},
        {"Stakeholder": "Software Producer", "Crisis Stance": "Compensating (Restitution Offerings)", "Score (1-5)": round(rec_means.get("Producer_Compensating", 0), 2)},
        {"Stakeholder": "User", "Crisis Stance": "Posturing (Advocacy / Outcry)", "Score (1-5)": round(rec_means.get("User_Posturing", 0), 2)},
        {"Stakeholder": "User", "Crisis Stance": "Compensating (Claims & Lawsuits)", "Score (1-5)": round(rec_means.get("User_Compensating", 0), 2)},
        {"Stakeholder": "User", "Crisis Stance": "Correcting (Alternative Software)", "Score (1-5)": round(rec_means.get("User_Correcting", 0), 2)}
    ]
    stage_dashboards["recovering"] = pd.DataFrame(rec_rows)

    # Stage 5: Outcomes
    sub_out = model_data[model_data["Stage"] == "Outcomes"]
    out_means = sub_out.mean(numeric_only=True) if not sub_out.empty else pd.Series(dtype=float)
    out_rows = [
        {"Stakeholder": "Regulator", "Dimension": "Costs", "Simulated Score": round(out_means.get("Regulator_OutCosts", 0), 2)},
        {"Stakeholder": "Regulator", "Dimension": "Transformations", "Simulated Score": round(out_means.get("Regulator_OutTransformations", 0), 2)},
        {"Stakeholder": "Regulator", "Dimension": "Remedies", "Simulated Score": round(out_means.get("Regulator_OutRemedies", 0), 2)},
        {"Stakeholder": "Regulator", "Dimension": "Preservation", "Simulated Score": round(out_means.get("Regulator_OutPreservation", 0), 2)},
        {"Stakeholder": "Software Producer", "Dimension": "Costs", "Simulated Score": round(out_means.get("Producer_OutCosts", 0), 2)},
        {"Stakeholder": "Software Producer", "Dimension": "Transformations", "Simulated Score": round(out_means.get("Producer_OutTransformations", 0), 2)},
        {"Stakeholder": "Software Producer", "Dimension": "Remedies", "Simulated Score": round(out_means.get("Producer_OutRemedies", 0), 2)},
        {"Stakeholder": "Software Producer", "Dimension": "Preservation", "Simulated Score": round(out_means.get("Producer_OutPreservation", 0), 2)},
        {"Stakeholder": "User", "Dimension": "Costs", "Simulated Score": round(out_means.get("User_OutCosts", 0), 2)},
        {"Stakeholder": "User", "Dimension": "Transformations", "Simulated Score": round(out_means.get("User_OutTransformations", 0), 2)},
        {"Stakeholder": "User", "Dimension": "Remedies", "Simulated Score": round(out_means.get("User_OutRemedies", 0), 2)},
        {"Stakeholder": "User", "Dimension": "Preservation", "Simulated Score": round(out_means.get("User_OutPreservation", 0), 2)}
    ]
    stage_dashboards["outcomes"] = pd.DataFrame(out_rows)

    print("\n" + "=" * 80)
    print("--- 2. STAGE-SPECIFIC BEHAVIORAL DASHBOARDS ---")
    print("=" * 80)
    print("\n[ STAGE 2: OPERATING (Routine Governance & Hygiene) ]")
    print(stage_dashboards["operating"].to_string(index=False))
    print("\n[ STAGE 3: PRECURSORS (Risk Drivers & Vulnerability Index) ]")
    print(stage_dashboards["precursors"].to_string(index=False))
    print("\n[ STAGE 4: RECOVERING (Crisis Management Stances) ]")
    print(stage_dashboards["recovering"].to_string(index=False))
    print("\n[ STAGE 5: OUTCOMES (Simulated Structural Legacy) ]")
    print(stage_dashboards["outcomes"].to_string(index=False))

    # -----------------------------------------------------------------
    # FINANCIAL & ENFORCEMENT LEDGER
    # -----------------------------------------------------------------
    latest = model_data.iloc[-1]
    fines = latest['Producer_TotalFinesPaid']
    comp_paid = latest['Producer_TotalCompPaid']
    net_cost = latest['Producer_NetCost']
    user_rec = latest['User_TotalCompReceived']
    restitution_pct = (comp_paid / net_cost * 100) if net_cost > 0 else 0.0

    ledger = {
        "Producer Total Fines Paid": fines,
        "Producer Total Compensation Paid": comp_paid,
        "Net Producer Financial Burden": net_cost,
        "User Total Compensation Received": user_rec,
        "Restitution Share of Producer Burden (%)": restitution_pct
    }

    print("\n" + "=" * 80)
    print("--- 3. FINANCIAL & ENFORCEMENT ACCOUNTING ---")
    print("=" * 80)
    for k, v in ledger.items():
        if "(%)" in k:
            print(f"  {k:<42}: {v:.1f}%")
        else:
            print(f"  {k:<42}: ${v:,.2f}")

    # -----------------------------------------------------------------
    # SIDE-BY-SIDE EMPIRICAL VALIDATION AUDIT SCORECARD
    # -----------------------------------------------------------------
    audit_rows = []
    alignment_score = 100.0
    mae = 0.0

    if scenario != "random" and scenario in EMPIRICAL_PROFILES:
        emp = EMPIRICAL_PROFILES[scenario]
        errors = []

        sh_mapping = [
            ("Regulator", "Regulator", "Regulator_Out"),
            ("Software Producer", "Software Producer", "Producer_Out"),
            ("User", "User", "User_Out")
        ]

        for display_name, sh_key, col_prefix in sh_mapping:
            emp_out = emp.get(sh_key, {}).get("Outcomes", {})
            for dim in ["Costs", "Transformations", "Remedies", "Preservation"]:
                benchmark_val = float(emp_out.get(dim, 3.0))
                col_name = f"{col_prefix}{dim}"
                sim_val = round(float(out_means.get(col_name, benchmark_val)), 2)
                diff = round(sim_val - benchmark_val, 2)
                abs_err = abs(diff)
                errors.append(abs_err)

                if abs_err == 0:
                    status = "[EXACT FIT]"
                elif abs_err <= 0.5:
                    status = "[CLOSE FIT]"
                elif abs_err <= 1.0:
                    status = "[MODERATE FIT]"
                else:
                    status = "[DIVERGENT]"

                audit_rows.append({
                    "Stakeholder": display_name,
                    "Dimension": dim,
                    "Benchmark (CSV)": benchmark_val,
                    "Simulated": sim_val,
                    "Delta": f"{'+' if diff > 0 else ''}{diff:.2f}",
                    "Status": status
                })

        audit_df = pd.DataFrame(audit_rows)
        mae = sum(errors) / len(errors) if errors else 0.0
        # 1-5 scale has maximum error of 4.0; alignment is 1 - MAE/4
        alignment_score = max(0.0, (1.0 - (mae / 4.0)) * 100.0)

        print("\n" + "=" * 80)
        print("--- 4. EMPIRICAL VALIDATION AUDIT SCORECARD ---")
        print("=" * 80)
        print(audit_df.to_string(index=False))
        print("-" * 80)
        print(f"  Model Empirical Alignment Score: {alignment_score:.1f}%")
        print(f"  Mean Absolute Error (MAE):       {mae:.3f} (on 1-5 scale)")
        print("=" * 80 + "\n")
    else:
        audit_df = pd.DataFrame()

    # -----------------------------------------------------------------
    # GENERATE MARKDOWN EXECUTIVE SUMMARY REPORT
    # -----------------------------------------------------------------
    report_path = os.path.join(output_dir, "summary_report.md")
    generate_markdown_report(
        report_path=report_path,
        config=config,
        df_initial=df_initial,
        trajectory_df=trajectory_df,
        stage_dashboards=stage_dashboards,
        audit_df=audit_df,
        alignment_score=alignment_score,
        mae=mae,
        ledger=ledger
    )
    print(f"Executive Markdown Summary saved to: {report_path}\n")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run 5-Stage Cybersecurity Compliance ABM.")
    parser.add_argument("--scenario", type=str, default="equifax_2017",
                        choices=list(EMPIRICAL_PROFILES.keys()) + ["random"],
                        help="Preset scenario name or 'random'.")
    parser.add_argument("--steps", type=int, default=30, help="Total simulation steps (default: 30).")
    parser.add_argument("--incident_step", type=int, default=10, help="Incident step (default: 10).")
    parser.add_argument("--seed", type=int, default=42, help="Random seed (default: 42).")
    parser.add_argument("--output", type=str, default="outputs", help="Output directory (default: 'outputs').")
    parser.add_argument("--monte_carlo", action="store_true", help="Execute Monte Carlo batch sweep using stochastic random scenarios.")
    parser.add_argument("--runs", type=int, default=100, help="Number of Monte Carlo iterations (default: 100).")

    args = parser.parse_args()

    if args.monte_carlo:
        from monte_carlo import run_monte_carlo
        mc_output = args.output if args.output != "outputs" else "outputs/monte_carlo"
        run_monte_carlo(
            runs=args.runs,
            steps=args.steps,
            incident_step=args.incident_step,
            base_seed=args.seed,
            output_dir=mc_output
        )
    else:
        run_simulation(
            scenario=args.scenario,
            steps=args.steps,
            incident_step=args.incident_step,
            seed=args.seed,
            output_dir=args.output
        )
